name: "Lock Issues"

on:
  issues:
    types: opened

permissions:
  issues: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v3
        with:
          close-issue: false
          process-only: "issues"
          issue-labels: "🔒 locked"
          exclude-issue-labels: "gssoc23"
          skip-closed-issue-comment: true
          issue-comment: >
            To reduce unwanted notifications your issue is locked. Your issue will be unlocked when we add the label, `gssoc23`.
