import React from "react"
import Circle from "./circle"
import Box from "./Box"
import Button from "./Button"
import Logo from "../Capture.PNG"

const FrontEnd=()=>{
	return (
		<div>
        <Circle top="50px" left="40px" />
        <Circle top="50px" left="140px" />
        <Circle top="150px" left="40px" />
        <Circle top="150px" left="140px" />

        <Circle top="50px" left="440px" />
        <Circle top="50px" left="550px" />
        <Circle top="150px" left="440px" />
        <Circle top="150px" left="550px" />

        <Circle top="450px" left="40px" />
        <Circle top="450px" left="140px" />
        <Circle top="550px" left="40px" />
        <Circle top="550px" left="140px" />

        <Circle top="450px" left="440px" />
        <Circle top="450px" left="550px" />
        <Circle top="550px" left="440px" />
        <Circle top="550px" left="550px" />

        <Box height="250px" width="250px" color="red" top="400px" left="0px" />
        <Box height="250px" width="250px" color="green" top="0px" left="0px" />
        <Box
          height="250px"
          width="250px"
          color="blue"
          top="400px"
          left="400px"
        />
        <Box
          height="250px"
          width="250px"
          color="yellow"
          top="0px"
          left="400px"
        />

        <div id="grid">
          <Box
            height="50px"
            dir="2"
            width="50px"
            type="N"
            color="white"
            top="0px"
            left="250px"
          />
          <Box
            height="50px"
            dir="0"
            width="50px"
            type="N"
            color="white"
            top="50px"
            left="250px"
          />
          <Box
            height="50px"
            dir="0"
            width="50px"
            type="N"
            color="white"
            top="100px"
            left="250px"
          />
          <Box
            height="50px"
            dir="0"
            width="50px"
            type="N"
            color="white"
            top="150px"
            left="250px"
          />
          <Box
            height="50px"
            dir="0"
            width="50px"
            type="N"
            color="white"
            top="200px"
            left="250px"
          />
          <Box
            height="50px"
            dir="2"
            width="50px"
            type="NS"
            color="white"
            top="0px"
            left="300px"
          />
          <Box
            height="50px"
            dir="4"
            width="50px"
            type="N"
            color="yellow"
            top="50px"
            left="300px"
          />
          <Box
            height="50px"
            dir="4"
            width="50px"
            type="N"
            color="yellow"
            top="100px"
            left="300px"
          />
          <Box
            height="50px"
            dir="4"
            width="50px"
            type="N"
            color="yellow"
            top="150px"
            left="300px"
          />
          <Box
            height="50px"
            dir="4"
            width="50px"
            type="N"
            color="yellow"
            top="200px"
            left="300px"
          />
          <Box
            height="50px"
            dir="4"
            width="50px"
            type="N"
            color="white"
            top="0px"
            left="350px"
          />
          <Box
            height="50px"
            dir="4"
            width="50px"
            type="S"
            color="yellow"
            top="50px"
            left="350px"
          />
          <Box
            height="50px"
            dir="4"
            width="50px"
            type="N"
            color="white"
            top="100px"
            left="350px"
          />
          <Box
            height="50px"
            dir="4"
            width="50px"
            type="N"
            color="white"
            top="150px"
            left="350px"
          />
          <Box
            height="50px"
            dir="3"
            width="50px"
            type="N"
            color="white"
            top="200px"
            left="350px"
          />

          <Box
            height="50px"
            dir="7"
            
            width="50px"
            type="N"
            color="white"
            top="400px"
            left="250px"
          />
          <Box
            height="50px"
            dir="0"
            width="50px"
            type="N"
            color="white"
            top="450px"
            left="250px"
          />
          <Box
            height="50px"
            dir="0"
            width="50px"
            type="N"
            color="white"
            top="500px"
            left="250px"
          />
          <Box
            height="50px"
            dir="0"
            width="50px"
            type="S"
            color="red"
            top="550px"
            left="250px"
          />
          <Box
            height="50px"
            dir="0"
            width="50px"
            type="N"
            color="white"
            top="600px"
            left="250px"
          />
          <Box
            height="50px"
            dir="0"
            width="50px"
            type="N"
            color="red"
            top="400px"
            left="300px"
          />
          <Box
            height="50px"
            dir="0"
            width="50px"
            type="N"
            color="red"
            top="450px"
            left="300px"
          />
          <Box
            height="50px"
            dir="0"
            width="50px"
            type="N"
            color="red"
            top="500px"
            left="300px"
          />
          <Box
            height="50px"
            dir="0"
            width="50px"
            type="N"
            color="red"
            top="550px"
            left="300px"
          />
          <Box
            height="50px"
            dir="6"
            width="50px"
            type="NS"
            color="white"
            top="600px"
            left="300px"
          />
          <Box
            height="50px"
            dir="4"
            width="50px"
            type="N"
            color="white"
            top="400px"
            left="350px"
          />
          <Box
            height="50px"
            dir="4"
            width="50px"
            type="N"
            color="white"
            top="450px"
            left="350px"
          />
          <Box
            height="50px"
            dir="4"
            width="50px"
            type="N"
            color="white"
            top="500px"
            left="350px"
          />
          <Box
            height="50px"
            dir="4"
            width="50px"
            type="N"
            color="white"
            top="550px"
            left="350px"
          />
          <Box
            height="50px"
            dir="6"
            width="50px"
            type="N"
            color="white"
            top="600px"
            left="350px"
          />

          <Box
            height="50px"
            dir="0"
            type="N"
            width="50px"
            color="white"
            top="350px"
            left="0px"
          />
          <Box
            height="50px"
            dir="6"
            type="N"
            width="50px"
            color="white"
            top="350px"
            left="50px"
          />
          <Box
            height="50px"
            dir="6"
            type="N"
            width="50px"
            color="white"
            top="350px"
            left="100px"
          />
          <Box
            height="50px"
            dir="6"
            type="N"
            width="50px"
            color="white"
            top="350px"
            left="150px"
          />
          <Box
            height="50px"
            dir="6"
            type="N"
            width="50px"
            color="white"
            top="350px"
            left="200px"
          />
          <Box
            height="50px"
            dir="0"
            type="NS"
            width="50px"
            color="white"
            top="300px"
            left="0px"
          />
          <Box
            height="50px"
            dir="2"
            type="N"
            width="50px"
            color="green"
            top="300px"
            left="50px"
          />
          <Box
            height="50px"
            dir="2"
            type="N"
            width="50px"
            color="green"
            top="300px"
            left="100px"
          />
          <Box
            height="50px"
            dir="2"
            type="N"
            width="50px"
            color="green"
            top="300px"
            left="150px"
          />
          <Box
            height="50px"
            dir="2"
            type="N"
            width="50px"
            color="green"
            top="300px"
            left="200px"
          />
          <Box
            height="50px"
            dir="2"
            type="N"
            width="50px"
            color="white"
            top="250px"
            left="0px"
          />
          <Box
            height="50px"
            dir="2"
            type="S"
            width="50px"
            color="green"
            top="250px"
            left="50px"
          />
          <Box
            height="50px"
            dir="2"
            type="N"
            width="50px"
            color="white"
            top="250px"
            left="100px"
          />
          <Box
            height="50px"
            dir="2"
            type="N"
            width="50px"
            color="white"
            top="250px"
            left="150px"
          />
          <Box
            height="50px"
            dir="1"
            type="N"
            width="50px"
            color="white"
            top="250px"
            left="200px"
          />

          <Box
            height="50px"
            dir="5"
            type="N"
            width="50px"
            color="white"
            top="350px"
            left="400px"
          />
          <Box
            height="50px"
            dir="6"
            type="N"
            width="50px"
            color="white"
            top="350px"
            left="450px"
          />
          <Box
            height="50px"
            dir="6"
            type="N"
            width="50px"
            color="white"
            top="350px"
            left="500px"
          />
          <Box
            height="50px"
            dir="6"
            type="S"
            width="50px"
            color="blue"
            top="350px"
            left="550px"
          />
          <Box
            height="50px"
            dir="6"
            type="N"
            width="50px"
            color="white"
            top="350px"
            left="600px"
          />
          <Box
            height="50px"
            dir="6"
            type="N"
            width="50px"
            color="blue"
            top="300px"
            left="400px"
          />
          <Box
            height="50px"
            dir="6"
            type="N"
            width="50px"
            color="blue"
            top="300px"
            left="450px"
          />
          <Box
            height="50px"
            dir="6"
            type="N"
            width="50px"
            color="blue"
            top="300px"
            left="500px"
          />
          <Box
            height="50px"
            dir="6"
            type="N"
            width="50px"
            color="blue"
            top="300px"
            left="550px"
          />
          <Box
            height="50px"
            dir="4"
            type="NS"
            width="50px"
            color="white"
            top="300px"
            left="600px"
          />
          <Box
            height="50px"
            dir="2"
            type="N"
            width="50px"
            color="white"
            top="250px"
            left="400px"
          />
          <Box
            height="50px"
            dir="2"
            type="N"
            width="50px"
            color="white"
            top="250px"
            left="450px"
          />
          <Box
            height="50px"
            dir="2"
            type="N"
            width="50px"
            color="white"
            top="250px"
            left="500px"
          />
          <Box
            height="50px"
            dir="2"
            type="N"
            width="50px"
            color="white"
            top="250px"
            left="550px"
          />
          <Box
            height="50px"
            dir="4"
            type="N"
            width="50px"
            color="white"
            top="250px"
            left="600px"
          />
        </div>

        
        {this.state.pawn.map((item, index) => {
          return (
            <div onClick={this.movepaw.bind(this, item)}>
              <Button state={item} key={index} />
            </div>
          );
        })}
        <button
          name="dice"
          onClick={this.Dice}
          style={{
            width: "50px",
            height: "50px",
            position: "absolute",
            top: "300px",
            left: "900px"
          }}
        >
          {this.state.pasa}
        </button>
        <img src={Logo} className="Logo" />
      </div>  
    );

		
}
export default FrontEnd